apiVersion: k6.io/v1alpha1
kind: K6
metadata:
    name: prod-line-sys-svc-stress-test
spec:
    parallelism: 20
    script: |
        import http from 'k6/http';
        import { check, sleep } from 'k6';

        export const options = {
          scenarios: {
            high_concurrency: {
              executor: 'constant-vus',
              vus: 50000,                // 50,000 VUs per pod
              duration: '45m',           // 20 pods × 50,000 VUs = 1,000,000 total
            },
          },
          thresholds: {
            http_req_duration: ['p(95)<5000'],
            http_req_failed: ['rate<0.1'],
          },
          noConnectionReuse: true,
          discardResponseBodies: true,
        };

        const payloads = Array.from({ length: 1000 }, (_, i) => 
          JSON.stringify({
            temperature: (Math.random() * 10).toFixed(2),
            timestamp: new Date(Date.now() - i * 1000).toISOString()
          })
        );

        export default function() {
          const url = 'http://prod-line-sys-svc:8080/api/v1/smart-buffer-tanks/temperature-measurement';
          const randomPayload = payloads[Math.floor(Math.random() * payloads.length)];
          
          const params = {
            headers: { 
              'Content-Type': 'application/json',
              'Connection': 'close'
            },
            timeout: '60s',
          };
          
          const res = http.post(url, randomPayload, params);
          
          check(res, {
            'status is 200': (r) => r.status === 200,
            'response time < 10s': (r) => r.timings.duration < 10000,
          });
          
          sleep(1);
        }
    resources:
        requests:
            memory: "8Gi"
            cpu: "4000m"
        limits:
            memory: "16Gi"
            cpu: "8000m"
