name: Build & Push prod-line-sys-svc Docker Image

on:
    push:
        branches:
            - main
            - master
            - svc/prod-line-sys-svc
        paths:
            - "milk-services/prod-line-sys/prod-line-sys-svc/**"
    pull_request:
        branches:
            - main
            - master
            - svc/prod-line-sys-svc
        paths:
            - "milk-services/prod-line-sys/prod-line-sys-svc/**"

env:
    IMAGE_NAME: prod-line-sys-svc

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: milk-services/prod-line-sys/prod-line-sys-svc
                  file: milk-services/prod-line-sys/prod-line-sys-svc/Dockerfile
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
                      ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
